### ISSUE TITLE
expo ble problem 

### ISSUE THREAD

**Issue by ehsan342** [demsr/expo-ble#1]
nothing is shown in expo go .can you solve this problem?

**Comment by demsr** [comment]
Hey @ehsan342 ,

i'm sorry but this project does not work with expo go. You need to build a "custom dev client" with expo's eas system. [Read here for more info](https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8)

**Comment by ehsan342** [comment]
ok .thanks for your quick response, i will  try and come back if I got an issue

**Comment by demsr** [comment]
@ehsan342 sure do. If you have an expo account and the eas-cli is installed on your system all you have to do is run: `eas build --profile preview`

**Comment by ehsan342** [comment]
yes i have both expo and eas cli now I'm building apk for testing
